# docker-compose-dev.yml: for dev environment only!
version: '2'

services:

  nginx-proxy:
    extends:
      file: docker-compose-base.yml
      service: nginx-proxy
    container_name: yourproject_nginx_proxy_dev
    networks:
      - dev

  php-apache-engine:
    extends:
      file: docker-compose-base.yml
      service: php-apache-engine
    build: ./docker/conf/dev/php-apache-engine
    container_name: yourproject_php_apache_engine_dev
    volumes:
        # dev only!
      - ./docker/conf/dev/php-apache-engine/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/conf/dev/php-apache-engine/ext-xdebug.ini:/usr/local/etc/php/conf.d/ext-xdebug.ini:ro
    environment:
      - VIRTUAL_HOST=dev.yourproject.com
    networks:
      - dev
    depends_on:
      - mysql

  mysql:
    extends:
      file: docker-compose-base.yml
      service: mysql
    container_name: yourproject_mysql_dev
    ports:
      # dev only!
      - 3307:3306
    volumes:
      # dev only!
      - ./docker/volumes/dev/mysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: database_name
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - dev

volumes:
  mysql: {}

networks:
  dev: {}