# |--------------------------------------------------------------------------
# | Orbit scripts commands
# |--------------------------------------------------------------------------
# |
# | This file describes the scripts commands of your project.
# | Feel free to add your own commands!
# |
# | https://github.com/gulien/orbit/
# |

commands:

  # |--------------------------------------------------------------------------
  # | orbit run script-fix-permissions-docker-sync
  # |--------------------------------------------------------------------------
  # |
  # | Fixes "www-data" permissions issues with Docker Sync.
  # |

  - use: "script-fix-permissions-docker-sync"
    run:
      {{ if and (ne "windows" .Os) (eq "true" .EnvFiles.Config.ENABLE_DOCKER_SYNC) }}
      - /bin/bash config/scripts/fix-permissions.sh
      {{ else if eq "windows" .Os }}
      - cmd.exe /c echo Skipping UID binding for "www-data" user with Docker Sync ...
      {{ else }}
      - echo Skipping UID binding for "www-data" with Docker Sync ...
      {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run script-fix-permissions-nginx
  # |--------------------------------------------------------------------------
  # |
  # | Fixes "www-data" permissions issues in the NGINX container.
  # |

  - use: "script-fix-permissions-nginx"
    run:
       {{ if ne "windows" .Os }}
       - /bin/bash config/scripts/fix-permissions.sh NGINX
       {{ else }}
       - cmd.exe /c echo Skipping UID binding for "www-data" user in the NGINX container ...
       {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run script-fix-permissions-php-fpm
  # |--------------------------------------------------------------------------
  # |
  # | Fixes "www-data" permissions issues in the PHP-FPM container.
  # |

  - use: "script-fix-permissions-php-fpm"
    run:
       {{ if ne "windows" .Os }}
       - /bin/bash config/scripts/fix-permissions.sh PHP-FPM
       {{ else }}
       - cmd.exe /c echo Skipping UID binding for "www-data" user in the PHP-FPM container ...
       {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run script-traefik-self-signed-certificate
  # |--------------------------------------------------------------------------
  # |
  # | Generates the self-signed certificate if current environment is "local".
  # |

  - use: "script-traefik-self-signed-certificate"
    run:
      {{ if eq "local" .EnvFiles.Config.ENV }}
      - docker-compose -p {{ .EnvFiles.Config.ENV }}{{ .Values.Project.name }} -f modules/toolbox/docker-compose.yml run toolbox /bin/sh -c /scripts/traefik-self-signed-certificate.sh
      {{ else if eq "windows" .Os }}
      - cmd.exe /c echo Skipping self-signed certificate generation ...
      {{ else }}
      - echo Skipping self-signed certificate generation ...
      {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run script-traefik-htdigest
  # |--------------------------------------------------------------------------
  # |
  # | Generates the .htdigest file which is used to authenticate on the Traefik
  # | dashboard.
  # |
  # | Only for environments <> "local".
  # |

  - use: "script-traefik-htdigest"
    run:
      {{ if ne "local" .EnvFiles.Config.ENV }}
      - docker-compose -p {{ .EnvFiles.Config.ENV }}{{ .Values.Project.name }} -f modules/toolbox/docker-compose.yml run toolbox /bin/sh -c  /scripts/traefik-htdigest.sh
      {{ else if eq "windows" .Os }}
      - cmd.exe /c echo Skipping .htdigest file generation ...
      {{ else }}
      - echo Skipping .htdigest file generation ...
      {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run script-graylog-secrets
  # |--------------------------------------------------------------------------
  # |
  # | Generates Graylog secrets.
  # |

  - use: "script-graylog-secrets"
    run:
      - docker-compose -p {{ .EnvFiles.Config.ENV }}{{ .Values.Project.name }} -f modules/toolbox/docker-compose.yml run toolbox /bin/sh -c /scripts/graylog-secrets.sh

  # |--------------------------------------------------------------------------
  # | orbit run script-graylog-health-check
  # |--------------------------------------------------------------------------
  # |
  # | Generates Graylog secrets.
  # |

  - use: "script-graylog-health-check"
    run:
      {{ if eq true .Values.Modules.graylog.enable }}
      - docker-compose -p {{ .EnvFiles.Config.ENV }}{{ .Values.Project.name }} -f modules/toolbox/docker-compose.yml run toolbox /bin/sh -c /scripts/graylog-health-check.sh
      {{ else if eq "windows" .Os }}
      - cmd.exe /c echo Skipping Graylog healtch check ...
      {{ else }}
      - echo Skipping Skipping Graylog healtch check ...
      {{ end }}