# |--------------------------------------------------------------------------
# | PHP application cross-environments configuration variables
# |--------------------------------------------------------------------------
# |
# | You can add here variables which are useful to configure your PHP
# | application.
# |