traefik:

  # |--------------------------------------------------------------------------
  # | Traefik user
  # |--------------------------------------------------------------------------
  # |
  # | The Traefik user used for generating the .htdigest file.
  # |
  # | Only required for environments <> "local".
  # |

  user: kickoff

graylog:

  # |--------------------------------------------------------------------------
  # | Enable Graylog
  # |--------------------------------------------------------------------------
  # |
  # | If true, enables Graylog.
  # |

  enable: true

  # |--------------------------------------------------------------------------
  # | Graylog user
  # |--------------------------------------------------------------------------
  # |
  # | The Graylog root user.
  # |

  user: kickoff

mysql:

  # |--------------------------------------------------------------------------
  # | Enable MySQL
  # |--------------------------------------------------------------------------
  # |
  # | If true, enables MySQL.
  # |

  enable: true

  # |--------------------------------------------------------------------------
  # | MySQL user
  # |--------------------------------------------------------------------------
  # |
  # | The MySQL user of your PHP application.
  # |

  user: kickoff

  # |--------------------------------------------------------------------------
  # | MySQL databases
  # |--------------------------------------------------------------------------
  # |
  # | List of the databases of your PHP application. If they do not exist,
  # | they will be created when the MySQL container starts.
  # |
  # | The previous user will have all privileges on these databases.
  # |

  databases:
    - my_awesome_database
    - my_genious_database
    - my_ok_database

redis:

  # |--------------------------------------------------------------------------
  # | Enable Redis
  # |--------------------------------------------------------------------------
  # |
  # | If true, enables Redis.
  # |

  enable: true

rabbitmq:

  # |--------------------------------------------------------------------------
  # | Enable RabbitMQ
  # |--------------------------------------------------------------------------
  # |
  # | If true, enables RabbitMQ.
  # |

  enable: true

  # |--------------------------------------------------------------------------
  # | RabbitMQ user
  # |--------------------------------------------------------------------------
  # |
  # | The RabbitMQ user of your PHP application.
  # |

  user: kickoff