version: '3.3'


services:


  toolbox:
    image: gulnap/kickoff-docker-php-images:toolbox-3.6-rc1
    container_name: {{ .EnvFiles.Kickoff.ENV }}-{{ .Values.Kickoff.project.name }}-toolbox
    restart: "no"
    networks:
      - backend
    environment:
      {{- range $env, $virtualhost := .Values.Kickoff.project.virtualhost }}
      {{- if eq $env $.EnvFiles.Kickoff.ENV }}
      - VIRTUAL_HOST={{ $virtualhost }}
      {{- end }}
      {{- end }}
      {{- if ne "local" .EnvFiles.Kickoff.ENV }}
      - TRAEFIK_USER={{ .Values.Kickoff.traefik.user }}
      - TRAEFIK_PASSWORD={{ .EnvFiles.Kickoff.TRAEFIK_PASSWORD }}
      {{- end }}
      - GRAYLOG_ROOT_PASSWORD_SHA2={{ .EnvFiles.Kickoff.GRAYLOG_PASSWORD }}
    labels:
      - traefik.enable=false
    volumes:
      - ./toolbox/generated:/generated:rw
      - ./toolbox/scripts:/scripts:ro


networks:


  backend:
    driver: bridge